# To get started:
#
# pip install -r requirements.txt
# mkdocs serve
# Or just see the README
#
# ----------------------------------------------------------------------
site_name: APTrust Registry
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
repo_url:  https://github.com/APTrust/registry-docs
nav:
  - Home: index.md
  - Code Structure: structure.md
  - Key Code Components: components.md
  - Requests: requests.md
  - Security:
      - security/index.md
      - security/roles.md
      - security/authentication.md
      - security/authorization.md
      - security/csrf.md
      - security/headers.md
  - User Management: user-management.md
  - Institution Management: institution-management.md
  - Deletion: deletion.md
  - Restoration: restoration.md
  - Requeing Work Items: requeuing.md
  - NSQ: nsq.md
  - Redis: redis.md
  - UI Components: ui-components.md
  - Database: database.md
  - Settings: settings.md
  - Testing: testing.md
